version: "3.8"
services:
  react_app:
    container_name: react_app
    image: react_app_template
    build: ./reactflow-fe
    ports:
      - "3000:3000"
  node_server:
    container_name: node_server
    image: node_server_template
    build:
      context: ./reactflow-be
    ports:
      - "3001:3001"
